name = "rss-aggregator"
main = "worker.js"
compatibility_date = "2026-02-16"

[[kv_namespaces]]
binding = "SIMPLE_RSS_CACHE"
id = "41da26268ef44df58c5343027b9bb397"

{
  "observability": {
    "enabled": true,
    "head_sampling_rate": 1,
    "logs": {
      "enabled": true,
      "head_sampling_rate": 1,
      "persist": true,
      "invocation_logs": true
    },
    "traces": {
      "enabled": true,
      "persist": true,
      "head_sampling_rate": 1
    }
  }
}
